<div class="col-md-7">
            <div class="box box-primary">
              <div class="box-header">
                <h3 class="box-title">Last Login Information:</h3>
              </div>
              <div class="box-body">
                <table id="self-login-history" class="table table-bordered table-hover">
                  <thead>
                  <tr>

                    <th>SL</th>
                    <th>Login Date - Time</th>
                    <th>Logout Date - Time</th>
                    <th>Session Time</th>

                  </tr>
                  </thead>
                    
                  <tbody>


                  
                  
                  
                  </tbody>
                  <tfoot>
                  <tr>

                    <th>SL</th>
                    <th>Login Date - Time</th>
                    <th>Logout Date - Time</th>
                    <th>Session Time</th>

                  </tr>
                  </tfoot>
                </table>
              </div>

            </div>
          </div>


<script type="text/javascript">
  
  // self-login-history--------------
      var dataTable = $('#self-login-history').DataTable( {
          "processing": true,
          "language": {
              "processing": "<div class='overlay'><i class='fa fa-refresh fa-spin'></i></div>"
               //add a loading image,simply putting <img src="loader.gif" /> tag.
          },
          "columnDefs": [ {
                "targets": 'no-sort',
                "orderable": false,
          } ], //desable sorting
          "bAutoWidth": false , 

          "serverSide": true,

          "ajax":{
            url :"/public/user/getselfhistory", // json datasource
            type: "post",  // method  , by default get
            error: function(){  // error handling
              $(".self-login-history-error").html("");
              $("#self-login-history").append('<tbody class="self-login-history-error"><tr><th colspan="3">No Record Found</th></tr></tbody>');
              $("#self-login-history_processing").css("display","none");
              
            },
            complete: function() {
              $('[data-toggle=confirmation]').confirmation({
              rootSelector: '[data-toggle=confirmation]',
              // other options
              });
            }
          }
        } );




</script>