<?php

 use App\Helper\Includes\NumberToWord;

include $this->getTemplatePath().'php_includes/db_conx.php';

  $hasSuccess = '';

  if (isset($_SESSION['success'])) {
      
      $_Success = $_SESSION['success'];

      $_SESSION['success'] = '';
    }

  if (isset($_SESSION['error'])) {
      
      $_Error = $_SESSION['error'];

      $_SESSION['error'] = '';
    }

  if (isset($_SESSION['msg'])) {
    
    $_Message = $_SESSION['msg'];

    $_SESSION['msg'] = '';
  }

    
?>


<?php
if ($auth['user']->img!="") {
    $usrimg = 'profileimg/'.$auth['user']->img;
  } else {
    $usrimg = 'dist/img/avatar.png';
  }
?>

<!DOCTYPE html>
<html>
<head>
  
<? print $this->fetch('/ui_includes/head.phtml'); ?>

  <!-- DataTables -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>plugins/datatables/dataTables.bootstrap.css">

  <style type="text/css">
    
    .profile-user-img{
      width: 150px;
    }
  </style>
  
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- --mod: menu wrapper custom end -->
  <? print $this->fetch('/ui_includes/main_navigation.phtml'); ?>
  <!-- --mod: menu wrapper custom end -->
  
  <div class="wrapper page-wrapper">

    <header class="main-header">
      <? print $this->fetch('/ui_includes/header.phtml'); ?>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <?// print $this->fetch('/ui_includes/leftpanel.phtml'); ?>

    <!-- Content Wrapper. Contains page content -->
   <div class="content-wrapper">
    <!-- Content Header (Page header) -->


    <!-- Main content -->


    <section class="content-header">

      <?php if (isset($_Error) && $_Error == 'error') { ?>
        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><? echo $_Message; ?></h4>
        </div>
      <?php } ?>


      <?php if (isset($_Success) && $_Success == 'success') { ?>
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <? echo $_Message;?>
        </div>
      <?php } ?>

      <?php if (isset($_Success) && $_Success == 2) { ?>
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          পণ্যটি সফলভাবে ডিলিট করা হয়েছে।
        </div>
      <?php } ?>
      

      <?php if (isset($_Success) && $_Success == 'created') { ?>
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-check"></i> Added!</h4>
          পণ্যটি সফলভাবে এন্ট্রি করা হয়েছে।
        </div>
      <?php } ?>

      <?php if (isset($_Success) && $_Success == 'addedqty') { ?>
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-check"></i> Added!</h4>
          সফলভাবে নতুন মজুদ যুক্ত করা হয়েছে।
        </div>
      <?php } ?>
      

      <?php if ($hasSuccess == 2) { ?>
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-check"></i> Updated!</h4>
          Successfully Updated!
        </div>
      <?php } ?>

      <?php if ($hasSuccess == 3) { ?>
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-check"></i> Deleted!</h4>
          Successfully deleted!
        </div>
      <?php } ?>
      <!-- /.row -->

      <div class="row">

        <div class="col-md-12">
          <div class="col-md-12">
            <div class="box box-primary">
              <div class="box-header">
                <h3 class="box-title">Login Information of<b> <? echo $user->name; ?></b>:</h3>
              </div>
              <div class="box-body">
                <table id="self-login-history" class="table table-bordered table-hover">
                  <thead>
                  <tr>

                    <th>SL</th>
                    <th>Login Date - Time</th>
                    <th>Logout Date - Time</th>
                    <th>Session Time</th>

                  </tr>
                  </thead>
                    
                  <tbody>


                  
                  
                  
                  </tbody>
                  <tfoot>
                  <tr>

                    <th>SL</th>
                    <th>Login Date - Time</th>
                    <th>Logout Date - Time</th>
                    <th>Session Time</th>

                  </tr>
                  </tfoot>
                </table>
              </div>

            </div>
          </div>

        </div>










      </div>
      <!-- /.row -->
      
    </section>


    
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->



  <!-- footer -->
  <? print $this->fetch('/ui_includes/footer.phtml'); ?>

  <!-- Control Sidebar -->
  <? print $this->fetch('/ui_includes/control-sidebar.phtml'); ?>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>bootstrap/js/bootstrap.min.js"></script>

<!-- bootstrap-confirmation.min.js -->

<script src="<?php echo htmlspecialchars($baseUrl); ?>bootstrap/js/bootstrap-confirmation.min.js"></script>

<!-- DataTables -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/datatables/dataTables.bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/slimScroll/jquery.slimscroll.min.js"></script>

<!-- FastClick -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/app.min.js"></script>
<!-- sidebar toggle -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/sidebar-toggle.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/demo.js"></script>



    <script type="text/javascript">
  
  // self-login-history--------------
      var dataTable = $('#self-login-history').DataTable( {
          "processing": true,
          "language": {
              "processing": "<div class='overlay'><i class='fa fa-refresh fa-spin'></i></div>"
               //add a loading image,simply putting <img src="loader.gif" /> tag.
          },
          "columnDefs": [ {
                "targets": 'no-sort',
                "orderable": false,
          } ], //desable sorting
          "bAutoWidth": false , 

          "serverSide": true,

          "ajax":{
            url :"/public/user/getuserhistory/<? echo $user->id; ?>", // json datasource
            type: "post",  // method  , by default get
            error: function(){  // error handling
              $(".self-login-history-error").html("");
              $("#self-login-history").append('<tbody class="self-login-history-error"><tr><th colspan="3">No Record Found</th></tr></tbody>');
              $("#self-login-history_processing").css("display","none");
              
            },
            complete: function() {
              $('[data-toggle=confirmation]').confirmation({
              rootSelector: '[data-toggle=confirmation]',
              // other options
              });
            }
          }
        } );




</script>




</body>
</html>