<?php

 use App\Helper\Includes\NumberToWord;
 use App\Helper\AdminDetails;

 use App\Models\FixedUsers;


include $this->getTemplatePath().'php_includes/db_conx.php';

  $hasSuccess = '';

  if (isset($_SESSION['success'])) {
      
      $_Success = $_SESSION['success'];

      $_SESSION['success'] = '';
    }

  if (isset($_SESSION['error'])) {
      
      $_Error = $_SESSION['error'];

      $_SESSION['error'] = '';
    }

  if (isset($_SESSION['msg'])) {
    
    $_Message = $_SESSION['msg'];

    $_SESSION['msg'] = '';
  }

?>


<?php
if ($auth['user']->img!="") {
    $usrimg = 'profileimg/'.$auth['user']->img;
  } else {
    $usrimg = 'dist/img/avatar.png';
  }
?>

<!DOCTYPE html>
<html>
<head>
  
<? print $this->fetch('/ui_includes/head.phtml'); ?>

  <style type="text/css">
    
    .profile-user-img{
      width: 150px;
    }
  </style>
  
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- --mod: menu wrapper custom end -->
  <?// print $this->fetch('/ui_includes/main_navigation.phtml'); ?>
  <!-- --mod: menu wrapper custom end -->
  
  <div class="wrapper page-wrapper">

    <header class="main-header">
      <? print $this->fetch('/ui_includes/header.phtml'); ?>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <? print $this->fetch('/ui_includes/leftpanel.phtml'); ?>

    <!-- Content Wrapper. Contains page content -->
   <div class="content-wrapper">
    <!-- Content Header (Page header) -->


    <!-- Main content -->


    <section class="content-header">

      <?php if (isset($_Error) && $_Error == 'error') { ?>
        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <? echo $_Message; ?>
        </div>
      <?php } ?>


      <?php if (isset($_Success) && $_Success == 'success') { ?>
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <? echo $_Message;?>
        </div>
      <?php } ?>

      <!-- /.row -->

      <div class="row">
        <div class="col-md-10">

          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-header">
              <h4>Setup <b><?= $designation; ?></b></h4>
            </div>
            <div class="box-body">
              <form class="form-horizontal" role="form" action="/setfixed/<?= $id ?>" method="post">
                <?php echo $csrf['field']; ?>

                <input type="hidden" name="incharge" value="<?= $id ?>">

                <div class="form-group <? if(isset($errors['name'])) echo 'has-error' ?>">
                  <label for="name" class="col-sm-3 control-label">Name</label>

                  <div class="col-sm-9">
                    <input name="name" type="text" required class="form-control" id="name" placeholder="Enter Name" value="<? if(isset($old['name'])) echo $old['name']; ?>">
                  
                    <? if(isset($errors['name'])) { ?>
                    <span class="help-block"><? echo $errors['name'][0]; ?></span>

                    <? } ?>
                  </div>

                  


                </div>

                <div class="form-group <? if(isset($errors['description'])) echo 'has-error' ?>">
                  <label for="description" class="col-sm-3 control-label">Description</label>

                  <div class="col-sm-9">
                    <input name="description" type="text" class="form-control" id="description" placeholder="Enter Description" value="<? if(isset($old['description'])) echo $old['description']; ?>">
                  
                    <? if(isset($errors['description'])) { ?>
                    <span class="help-block"><? echo $errors['description'][0]; ?></span>

                    <? } ?>
                  </div>

                  


                </div>


                
                <div class="form-group <? if(isset($errors['mobile'])) echo 'has-error' ?>">
                  <label for="mobile" class="col-sm-3 control-label">Mobile Number</label>

                  <div class="col-sm-9">
                    <input name="mobile" type="text" class="form-control" id="mobile" placeholder="Enter Mobile Number" value="<? if(isset($old['mobile'])) echo $old['mobile']; ?>">
                  
                    <? if(isset($errors['mobile'])) { ?>
                    <span class="help-block"><? echo $errors['mobile'][0]; ?> </span>

                    <? } ?>
                  </div>

                  


                </div>


                <div class="form-group <? if(isset($errors['email'])) echo 'has-error' ?>">
                  <label for="email" class="col-sm-3 control-label">Email</label>

                  <div class="col-sm-9">
                    <input name="email" type="email" class="form-control" id="email" placeholder="Enter Email" value="<? if(isset($old['email'])) echo $old['email']; ?>">
                  
                    <? if(isset($errors['email'])) { ?>
                    <span class="help-block"><? echo $errors['email'][0]; ?></span>

                    <? } ?>
                  </div>
                </div>
                

                <div class="form-group <? if(isset($errors['address'])) echo 'has-error' ?>">
                  <label for="address" class="col-sm-3 control-label">Address</label>

                  <div class="col-sm-9">
                    <input name="address" type="text" class="form-control" id="address" placeholder="Enter Address" value="<? if(isset($old['address'])) echo $old['address']; ?>">
                  
                    <? if(isset($errors['address'])) { ?>
                    <span class="help-block"><? $errors['address'][0]; ?></span>

                    <? } ?>
                  </div>
                </div>

                <button type="submit" class="btn btn-success col-sm-5 pull-right" style="margin-top: 0px;"><i class="fa fa-check"></i> Setup User</button>  
              </form>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
          <!-- <p class=""><b>ঠিকানা</b></p> <p class="text-right"><a><?php echo $address; ?></a></p> -->

          
        </div>


        <!-- /.col -->

        <!-- /.col -->

        <!-- --------------------- modals block for edit profile --------------------- -->
















      </div>

      <div class="row">

        <?// include $this->getTemplatePath().'/modules/user/AdminAllUsers.phtml'; ?>

      </div>
      <!-- /.row -->

      <div class="row">

        <?// include $this->getTemplatePath().'/modules/user/AdminRoles.phtml'; ?>

      </div>
      <!-- /.row -->
      
    </section>


    
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->



  <!-- footer -->
  <? print $this->fetch('/ui_includes/footer.phtml'); ?>

  <!-- Control Sidebar -->
  <? print $this->fetch('/ui_includes/control-sidebar.phtml'); ?>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>bootstrap/js/bootstrap.min.js"></script>

<!-- bootstrap-confirmation.min.js -->

<script src="<?php echo htmlspecialchars($baseUrl); ?>bootstrap/js/bootstrap-confirmation.min.js"></script>

<!-- DataTables -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/datatables/dataTables.bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/slimScroll/jquery.slimscroll.min.js"></script>

<!-- FastClick -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/app.min.js"></script>
<!-- sidebar toggle -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/sidebar-toggle.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/demo.js"></script>

<script>

    //data table for products

  $(document).ready(function() {

      //edit sequrity question
      //triggered when modal is about to be shown
      var securityId = null;

      $(document).on("click", "#securityClose", function () {

          //get data-id attribute of the clicked element
          securityId = null;
          $("#securityQusId").val('');
          $('#securityChkPassword').val('');
          $("#passwordErr").html("");
          $("#securityQuestion").val('');
          $("#securityAnswer").val('');
          $("#securityAction").hide();
          $("#securitybox").hide();


      });

      

      $(document).on("click", "#securityedit", function () {

          //get data-id attribute of the clicked element
          securityId = $(this).data('ques-id');

          
          $("#securityQusId").val(securityId);

      });

      $(document).on("click", "#securityChkpass", function () {

          //get data-id attribute of the clicked element
          var pass = $('#securityChkPassword').val();

          jQuery.ajax({

            url : '/public/auth/checkpass',
            type : 'post',
            data : {
              pass :  pass
            },
            success : function(data) {
                  
                    if (data=='valid') {

                      $("#passwordErr").html("");

                      editQuestion(securityId);

                      $("#securitybox").show();
                      $("#securityAction").show();
                      // $("#securityQusDel").attr('href', '/user/deletequs/'+securityId)

                    } else {

                      $("#passwordErr").html("Wrong Password!");
                      $("#securityAction").hide();
                      $("#securitybox").hide();
                    }
                  
                    
                  }
              
          });  

      });

      function editQuestion(id) {
        
        jQuery.ajax({

            url : '/public/user/getquestion',
            type : 'post',
            data : {
              id :  id
            },
            success : function(data) {

                  
                     var question = JSON.parse(data);

                      $("#securityQuestion").val(question.question);

                      $("#securityAnswer").val(question.answer);
                  
                    
                  }
              
          });

      }

      $('[data-toggle=confirmation]').confirmation({
              rootSelector: '[data-toggle=confirmation]',
              // other options
              onConfirm: function() {

                window.location.replace('/user/deletequs/'+securityId);
              
              }
      });


        //show modal if validation error!!

        <?
        if (isset($_SESSION['show_modal']) && $_SESSION['show_modal']=='editProfile') {
        ?>
          $('#editProfile').modal('show');

        <?

        $_SESSION['show_modal'] = '';

         } ?>

        <?
        if (isset($_SESSION['show_modal']) && $_SESSION['show_modal']=='addSecurityQus') {
        ?>
          $('#addSecurityQus').modal('show');

        <?

        $_SESSION['show_modal'] = '';

         } ?>

         <?
        if (isset($_SESSION['show_modal']) && $_SESSION['show_modal']=='addUser') {
        ?>
          $('#addUser').modal('show');

        <?

        $_SESSION['show_modal'] = '';

         } ?>
         
         



        $('#username').keyup(function () {

            var username = jQuery('#username').val();

              jQuery("#usernameWarning").hide();

              jQuery("#usernamecheckok").hide();
                      
              jQuery("#usernamecheck").show();

              jQuery.ajax({
                  url : '/public/user/checkusername',
                  type : 'post',
                  data : {
                    username : username
                  },
                  success : function(data) {
                    
                        jQuery("#usernamecheck").hide();
                          
                            if(data=='taken'){
                                jQuery("#usernameWarning").show();
                                jQuery("#usernameWarning").html("This username has already been used. Please use a different one.");
                                
                            }
                            if(data=='nottaken'){
                                jQuery("#usernamecheckok").show();


                            } 
                          
                        }
                    
               });

            

          });

        //for creating new user

        $('#newusername').keyup(function () {

            var username = jQuery('#newusername').val();

          
              jQuery("#newusernameWarning").hide();

              jQuery("#newusernamecheckok").hide();
                      
              jQuery("#newusernamecheck").show();

              jQuery.ajax({
                  url : '/public/user/checkusername',
                  type : 'post',
                  data : {
                    username : username
                  },
                  success : function(data) {
                    
                        jQuery("#newusernamecheck").hide();
                          
                            if(data=='taken'){
                                jQuery("#newusernameWarning").show();
                                jQuery("#newusernameWarning").html("This username has already been used. Please use a different one.");
                                
                            }
                            if(data=='nottaken'){
                                jQuery("#newusernamecheckok").show();
                            }  
                        }
               });      
          });



        $(document).on("click", "#changepasswordCheck", function () {

          //get data-id attribute of the clicked element
          var pass = $('#changePasswordCurrent').val();

          jQuery.ajax({

            url : '/public/auth/checkpass',
            type : 'post',
            data : {
              pass :  pass
            },
            success : function(data) {
                  
                    if (data=='valid') {

                      $("#changepasswordErr").html("");

                      $("#changepasswordBox").show();
                      $("#changepasswordAction").show();
                      // $("#securityQusDel").attr('href', '/user/deletequs/'+securityId)

                    } else {

                      $("#changepasswordErr").html("Wrong Password!");
                      $("#changepasswordBox").hide();
                      $("#changepasswordAction").hide();
                    }
                  
                    
                  }
              
          });  

        });

        
        
        
      } );
</script>



</body>
</html>