<?

if ($auth['user']->img!="") {
    $usrimg = 'profileimg/'.$auth['user']->img;
  } else {
    $usrimg = 'dist/img/avatar.png';
  }

use App\Models\ConfigData;

use App\Helper\AdminDetails;



?>

<!-- Logo -->
    <a href="/" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">eLeave System in HSTU</span>
      <!-- logo for regular state and mobile devices -->
      <!-- <span class="logo-lg">rrrLab - EMS</span> -->
      <span class="logo-lg">eLeave System HSTU</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          

            <li class="dropdown notifications-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-bell-o"></i>
                <span class="label label-danger" id="notification"></span>
              </a>
              <ul class="dropdown-menu">
                <li class="header" id="notf_title"></li>
                <li>
                  <!-- inner menu: contains the actual data -->
                  <ul class="menu" id="notf_invoices">
                    
                  </ul>
                </li>
                <li class="footer"><a href="#">View all</a></li>
              </ul>
            </li>


            <li class="dropdown tasks-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-flag-o"></i>
                <span class="label label-danger servicing_tasks"></span>
              </a>
              <ul class="dropdown-menu">
                <li class="header">You have <span class="servicing_tasks">0</span> tasks</li>
                <li>
                  <!-- inner menu: contains the actual data -->
                  <ul class="menu" id="notf_tasks">
                    
                  </ul>
                </li>
                <li class="footer">
                  <a href="/servicing/mytasks">View All Tasks</a>
                </li>
              </ul>
            </li>


          <!-- Tasks: style can be found in dropdown.less -->
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="<?php echo $baseUrl. $usrimg; ?>" class="user-image" alt="User Image">
              <span class="hidden-xs"><?php echo $auth['user']->name; ?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="<?php echo $baseUrl. $usrimg; ?>" class="img-circle" alt="User Image">

                <p>
                  <?php echo $auth['user']->name; ?>
                  <small><?php echo $auth['user']->description; ?></small>

                  <? if (AdminDetails::checkIfChairman($_SESSION['user'])): ?>
                    <small><b>Chairman, Dept. of <?= AdminDetails::getTeacherInfo($_SESSION['user'])->department_name ?></b></small>
                  <? endif ?>
                  <? if (AdminDetails::checkIfDean($_SESSION['user'])): ?>
                    <small><b>Dean, Faculty of <?= AdminDetails::getTeacherInfo($_SESSION['user'])->faculty_name ?></b></small>
                  <? endif ?>
                </p>
                
              </li>
              <!-- Menu Body -->
              
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="/user" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="/logout" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>