<?php

use App\Models\Admin;
use App\Helper\AdminDetails;

if ($auth['user']->img!="") {
    $usrimg = 'profileimg/'.$auth['user']->img;
  } else {
    $usrimg = 'dist/img/avatar.png';
  }

?>

<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<?php echo $baseUrl.$usrimg; ?>" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?php echo $auth['user']->name; ?></p>
          <a><i class="fa fa-circle text-success"></i> Online</a><br>
        </div>
      </div>
      
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        
        <? if (AdminDetails::checkIfChairman($_SESSION['user'])): ?>
          <p class="text-center"><b>Chairman</b></p>
        <? endif ?>

        <? if (AdminDetails::checkIfDean($_SESSION['user'])): ?>
          <p class="text-center"><b>Dean</b></p>
        <? endif ?>
        <? if (Admin::find($_SESSION['user'])->designation=='Registrar'): ?>
          <p class="text-center"><b>Registrar</b></p>
        <? endif ?>
        
        <li class="header">Main menu</li>
        <li class="<?php if($_SERVER['REQUEST_URI']=="/"){echo "active";} ?> treeview menuparent">
          <a href="/">
            <i class="fa fa-dashboard"></i> <span>Home</span>
          </a>
        </li>

        <? if($_SESSION['type']=="Academic"): ?>

        <li class="<?php if($_SERVER['REQUEST_URI']=="/newapplication"){echo "active";} ?> treeview menuparent">
          <a href="/newapplication">
            <i class="fa fa-edit"></i> <span>Write New Application</span>
          </a>
        </li>

        <li class="<?php if($_SERVER['REQUEST_URI']=="/allapplications"){echo "active";} ?> treeview menuparent">
          <a href="/allapplications">
            <i class="fa fa-th-list"></i> <span>All Applications</span>
          </a>
        </li>
        <li class="<?php if($_SERVER['REQUEST_URI']=="/alldrafts"){echo "active";} ?> treeview menuparent">
          <a href="/alldrafts">
            <i class="fa  fa-list-alt"></i> <span>Draft Applications</span>
          </a>
        </li>

      <? endif ?>



       

       

         <!-- Customers -->
        <?
        if($_SESSION['type']=="Main Admin"){
        ?>
        <li class="treeview menuparent <?php if($_SERVER['REQUEST_URI']=="/user/adduser" || $_SERVER['REQUEST_URI']=="/user/allusers"){echo "active";} ?>">
          <a href="#">
            <i class="fa fa-users"></i>
            <span>Users Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right arrowicon"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="<?php if($_SERVER['REQUEST_URI']=="/user/allusers"){echo "active";} ?>"><a href="/user/allusers"><i class="fa fa-circle-o"></i>All Users</a></li>

            <li class="<?php if($_SERVER['REQUEST_URI']=="/user/adduser"){echo "active";} ?>"><a href="/user/adduser"><i class="fa fa-plus-circle"></i> Add User</a></li>

            <li class="<?php if($_SERVER['REQUEST_URI']=="/user/fixeduser"){echo "active";} ?>"><a href="/user/fixeduser"><i class="fa fa-book"></i>Fixed Users</a></li>
            <li class="<?php if($_SERVER['REQUEST_URI']=="/user/teachers"){echo "active";} ?>"><a href="/user/teachers"><i class="fa fa-book"></i>Teachers</a></li>
 
          </ul>
        </li>
        <?
        }
        ?>

        <?
        $user = Admin::find($_SESSION['user']);
         if($user->designation=='VC' || $user->designation=='Registrar'): ?>

          <li class="<?php if($_SERVER['REQUEST_URI']=="/allteachers"){echo "active";} ?> treeview menuparent">
            <a href="/allteachers">
              <i class="fa fa-users"></i> <span>All Teachers</span>
            </a>
          </li>

          <li class="<?php if($_SERVER['REQUEST_URI']=="/teachersonleave"){echo "active";} ?> treeview menuparent">
            <a href="/teachersonleave">
              <i class="fa fa-plane"></i> <span>Teachers On Leave</span>
            </a>
          </li>
          

        <? endif ?>

        <? if (AdminDetails::checkIfChairman($_SESSION['user'])): ?>
          <li class="<?php if($_SERVER['REQUEST_URI']=="/allteachersbydept"){echo "active";} ?> treeview menuparent">
            <a href="/allteachersbydept">
              <i class="fa fa-users"></i> <span>All Teachers</span>
            </a>
          </li>

          <li class="<?php if($_SERVER['REQUEST_URI']=="/teachersonleavebydept"){echo "active";} ?> treeview menuparent">
            <a href="/teachersonleavebydept">
              <i class="fa fa-plane"></i> <span>Teachers On Leave</span>
            </a>
          </li>
        <? endif ?>


        <? if (AdminDetails::checkIfDean($_SESSION['user'])): ?>
          <li class="<?php if($_SERVER['REQUEST_URI']=="/allteachersbyfc"){echo "active";} ?> treeview menuparent">
            <a href="/allteachersbyfc">
              <i class="fa fa-users"></i> <span>All Teachers</span>
            </a>
          </li>

          <li class="<?php if($_SERVER['REQUEST_URI']=="/teachersonleavebyfc"){echo "active";} ?> treeview menuparent">
            <a href="/teachersonleavebyfc">
              <i class="fa fa-plane"></i> <span>Teachers On Leave</span>
            </a>
          </li>
        <? endif ?>
        


        


       
        
                                  <!-- for emoloyees -->
        <li class="treeview menuparent <?php if($_SERVER['REQUEST_URI']=="/user"){echo "active";} ?>">
          <a href="/user">
            <i class="fa fa-user"></i> <span>Profile</span>
            
          </a>
        </li>
       
        

        
        
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>