<!DOCTYPE html>
<html>
<head>
  
<? print $this->fetch('/ui_includes/head.phtml'); ?>


<!-- Morris chart -->
  <link rel="stylesheet" href="plugins/morris/morris.css">
</head>
<body class="hold-transition skin-blue sidebar-mini">

  <!-- --mod: menu wrapper custom end -->
  <? print $this->fetch('/ui_includes/main_navigation.phtml'); ?>
  <!-- --mod: menu wrapper custom end -->
  
  <div class="wrapper page-wrapper">

    <header class="main-header">
      <? print $this->fetch('/ui_includes/header.phtml'); ?>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <?// print $this->fetch('/ui_includes/leftpanel.phtml'); ?>

    <!-- Content Wrapper. Contains page content -->
   <div class="content-wrapper">
      <!-- Content Header (Page header)-->



       <section class="content-header">
        <h1>
          Dashboard
          <small>Control panel</small>
        </h1>
        <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
          <li class="active">Dashboard</li>
        </ol>
      </section>


      <section class="content">
        
        <!-- Small boxes (Stat box) -->
        <div class="row">
        	<?

        	echo "hello ";
        	echo $userid;
        	?>
         
        </div>






        <!-- test start-------- -->



      </section>


      <div class="col-md-12 bg-danger">
        

        <!-- test -->
        <!-- <h3 class="text-red text-center ">------------- CONTENT -------------</h3> -->

      </div>


        
    </div>





           




    <!-- footer -->
    <? print $this->fetch('/ui_includes/footer.phtml'); ?>

    <!-- Control Sidebar -->
    <? print $this->fetch('/ui_includes/control-sidebar.phtml'); ?>
    <!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
  </div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>bootstrap/js/bootstrap.min.js"></script>

<!-- Sparkline -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/sparkline/jquery.sparkline.min.js"></script>

<!-- jQuery Knob Chart -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/knob/jquery.knob.js"></script>
<!-- daterangepicker -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/moment.min.js"></script>
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/datepicker/bootstrap-datepicker.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

<!-- FastClick -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/app.min.js"></script>
<!-- sidebar toggle -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/sidebar-toggle.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/demo.js"></script>
<script src="<?php echo htmlspecialchars($baseUrl); ?>dist/js/zebra_datepicker.min.js"></script>

<!-- Morris.js charts -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>/dist/js/raphael-min.js"></script>
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/morris/morris.min.js"></script>
</body>
</html>