<?

$hasSuccess = '';

  if (isset($_SESSION['success'])) {
      
      $_Success = $_SESSION['success'];

      $_SESSION['success'] = '';
    }

  if (isset($_SESSION['error'])) {
      
      $_Error = $_SESSION['error'];

      $_SESSION['error'] = '';
    }

  if (isset($_SESSION['msg'])) {
    
    $_Message = $_SESSION['msg'];

    $_SESSION['msg'] = '';
  }

?>




<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>eLeave Sytem in HSTU | Login</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>dist/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>dist/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>dist/css/AdminLTE.min.css">

  <!-- iCheck -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>plugins/iCheck/flat/blue.css">
  <!-- Morris chart -->

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/home"><img src="/images/hstu_correct_logo.png" width="120"></a>
    <br>
    <a><b>eLeave Sytem in HSTU</b></a>
  </div>
  <div class="lockscreen-logo">
    <a>Admin LOGIN</a><br>
  </div>
  <section class="content-header">
      
    <?php if (isset($_Error) && $_Error == 'error') { ?>
      <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <? echo $_Message; ?>
      </div>
    <?php } ?>


    <?php if (isset($_Success) && $_Success == 'success') { ?>
      <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <? echo $_Message;?>
      </div>
    <?php } ?>
    
  </section>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Please Login to Your Account</p>

    <form action="/login" method="post" class="mt-5 mb-5 login-input">
                                    <?= $csrf['field']; ?>
                                    <div class="form-group has-feedback <? if(isset($errors['username'])) echo 'has-error' ?>">
        <input type="username" id="username" name="username" class="form-control" placeholder="Enter Username" value="<? if(isset($old['username'])) echo $old['username']; ?>">
        
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
        <? if(isset($errors['username'])) { ?>
        <span class="help-block"><? //echo $errors['username'][0]; ?> Please enter your userame </span>

        <? } ?>
      </div>

      <div class="form-group has-feedback <? if(isset($errors['password']) || isset($errors['loginerror'])) echo 'has-error' ?>">
        <input type="password" id="password" name="password" class="form-control" placeholder="Enter Password" value="<? if(isset($old['password'])) echo $old['password']; ?>">
        
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>

        <? if(isset($errors['password'])) { ?>
        <span class="help-block"><? //echo $errors['password'][0]; ?>Please Enter Password</span>

        <? } ?>

        <? if(isset($errors['loginerror'])) { ?>
        <span class="help-block"><? if($errors['loginerror']=='1') { echo 'Invalid Username!'; } else { echo 'Invalid Password!'; }?></span>

        <? } ?>
      </div>
      <button class="btn btn-success submit col-sm-12">Sign In</button>
                                </form>



    <br>
    <p class="text-red text-center" id="warning"></p>
    <br>
    <div class="text-center">
      <p class="mt-5 login-form__footer">If you are a faculty member of HSTU but dont have an account then <a href="/register" class="text-primary">Sign Up</a></p>
    </div>
    

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
<div class="lockscreen-footer text-center">
    Copyright &copy; <b><a href="http://rrrlab.com" target="_blank" class="text-black">rrrLab</a></b><br>
    All rights reserved
  </div>

<!-- jQuery 2.2.3 -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>bootstrap/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/iCheck/icheck.min.js"></script>
</body>
</html>






