<?
include $this->getTemplatePath().'php_includes/db_conx2.php';

?>

<?

$hasSuccess = '';

  if (isset($_SESSION['success'])) {
      
      $_Success = $_SESSION['success'];

      $_SESSION['success'] = '';
    }

  if (isset($_SESSION['error'])) {
      
      $_Error = $_SESSION['error'];

      $_SESSION['error'] = '';
    }

  if (isset($_SESSION['msg'])) {
    
    $_Message = $_SESSION['msg'];

    $_SESSION['msg'] = '';
  }

?>



<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>LeaveApp HSTU | Register</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>dist/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>dist/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>dist/css/AdminLTE.min.css">

  <!-- iCheck -->
  <link rel="stylesheet" href="<?php echo htmlspecialchars($baseUrl); ?>plugins/iCheck/flat/blue.css">
  <!-- Morris chart -->

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a><b>LeaveApp</b> for <b>HSTU</b></a>
    <hr>
  </div>
  <div class="lockscreen-logo">
    <a>Admin Register</a><br>
  </div>
  <section class="content-header">
      
    <?php if (isset($_Error) && $_Error == 'error') { ?>
      <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <? echo $_Message; ?>
      </div>
    <?php } ?>


    <?php if (isset($_Success) && $_Success == 'success') { ?>
      <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <? echo $_Message;?>
      </div>
    <?php } ?>
    
  </section>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Register as Faculty Member</p>

    <form action="/register" method="post" class="mt-5 mb-5 login-input">
	<?= $csrf['field']; ?>

	<div class="form-group">
		<select name="faculty" id="faculty" class="form-control" required="">
			<option value="">Select Faculty</option>
			<?
			$sql = "SELECT * FROM `faculty` WHERE status='A'";

			$result = mysqli_query($db_conx,$sql );

			$total_result = mysqli_num_rows($result);


			if ($total_result>0) {
				while($row = mysqli_fetch_array($result)){
				?>
				<option value="<?= $row['faculty_id'] ?>"><?= $row['faculty_name'] ?></option>
				<?}
			}?>
		
		
		</select>
	</div>
	<div class="form-group">
		<select name="department" id="department" class="form-control" required>
			<option value="">Select Departmen</option>
		</select>
	</div>

	<div class="form-group">
		<select name="teacher" id="teacher" name="teacher" class="form-control" required>
			<option value="">Select Yourself</option>
		</select>
	</div>
	<p style="display: none;" id="emailfield"><b>Your Email: </b><span id="emailuser"></span></p>
	<div class="form-group">
		<input type="email" name="email" class="form-control" placeholder="enter your email" required>
	</div>
	<button class="btn btn-success btn-sm col-sm-12">Register</button>
</form>


    <br>
    <p class="text-red text-center" id="warning"></p>
    <br>
    <div class="text-center">
      <p class="mt-5 login-form__footer">Have account? <a href="/login" class="text-primary">Login </a> now</p>
    </div>
    

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
<div class="lockscreen-footer text-center">
    Copyright &copy; <b><a href="http://rrrlab.com" target="_blank" class="text-black">rrrLab</a></b><br>
    All rights reserved
  </div>

<!-- jQuery 2.2.3 -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>bootstrap/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="<?php echo htmlspecialchars($baseUrl); ?>plugins/iCheck/icheck.min.js"></script>

	<script>
		$("#faculty").change(function(){
			jQuery.ajax({
              url : '/public/auth/getdepartments',
              type : 'post',
              data : {
                faculty :        $(this).val(),
              },
              success : function(data) {

                $("#department").html(data);
                
              } 
        });
		})

		$("#department").change(function(){
			jQuery.ajax({
              url : '/public/auth/getteachers',
              type : 'post',
              data : {
                department :        $(this).val(),
              },
              success : function(data) {

                $("#teacher").html(data);
                
              } 
        });
		})

		$("#teacher").change(function(){
			jQuery.ajax({
              url : '/public/auth/getteacheremail',
              type : 'post',
              data : {
                teacher :        $(this).val(),
              },
              success : function(data) {
              	if (data=='noemail') {
              		$("#emailuser").html("You have not updated your email address in HSTU database. Please contact IT cell for updating your email address.");
              		$("#emailfield").show();
              	} else {
              		$("#emailfield").show();
              		$("#emailuser").html(data);

              	}
                
                
              } 
        });
		})
		
	</script>
</body>
</html>




